# Generated by Django 4.1.7 on 2023-05-16 09:27

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg"]
                            )
                        ],
                        verbose_name="image",
                    ),
                ),
                ("acivation_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="BookTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("journey", models.CharField(blank=True, max_length=100, null=True)),
                ("seats", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "slected_seat",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fare", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("book_date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "departure_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "arrival_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=500)),
                ("bus_number", models.CharField(max_length=15)),
                (
                    "bus_category",
                    models.CharField(
                        choices=[("Local", "Local"), ("Express", "Express")],
                        max_length=20,
                    ),
                ),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("Ac-seating", "Ac-seating"),
                            ("Non-Ac-seating", "Non-Ac-seating"),
                            ("Ac-sleeping", "Ac-slepping"),
                            ("Non-Ac-sleeping", "Non-Ac-slepping"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bus_seat", models.CharField(max_length=10, null=True)),
                ("bus_status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="JourneyRoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_point", models.CharField(max_length=100000)),
                ("end_point", models.CharField(max_length=1000000)),
                ("kilometer", models.CharField(max_length=10)),
                (
                    "one_kilometer_price",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("price", models.CharField(blank=True, max_length=10, null=True)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("via", models.CharField(blank=True, max_length=1000, null=True)),
                ("bus", models.ManyToManyField(related_name="buses", to="core.bus")),
            ],
        ),
        migrations.CreateModel(
            name="CancleTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancle_bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bookticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bookticket",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.bus",
            ),
        ),
        migrations.AddField(
            model_name="bookticket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
