from django.urls import path
from . import views
from .views import *
urlpatterns=[
    path("home/",views.HomeView.as_view(),name="home"),
    path('change_password/',ChangePassword.as_view(),name="change_password"),
    path('forget_password1/',MainForgetPassword.as_view(),name="forget_password1"),
    path('',LoginView.as_view(),name="login1"),
    path("account/<int:id>/",Account.as_view(),name="account"),
    path('register/',Register.as_view(),name="register"),
    path('register1/',MainRegister.as_view(),name="register1"),
    path("user-register/",CommonUserRegister.as_view(),name="user-register"),
    path('form1/',BusAdd.as_view(),name="form1"),
    path('seat/<int:id>/',Seat.as_view(),name="seat"),
    path('ticket_details/',TicketDetails.as_view(),name="ticket_details"),
    path('bookbus/<int:id>/',BusBook.as_view(),name="bookbus"),
    path('search_bus/',SearchBus.as_view(),name="search_bus"),
    path('form2/',JourneyAdd.as_view(),name="form2"),
    path("logout/",LoginView.as_view(),name="logout"),
    path("logout1/",logout1,name="logout1"),
    path("admin_list/",AdminUserList.as_view(),name="admin_list"),
    path("staff_list/",StaffUserList.as_view(),name="staff_list"),
    path("bus_list/",BusList.as_view(),name="bus_list"),
    path("book_ticket_list/",TicketDetailsAdmin.as_view(),name="book_ticket_list/"),
    path("journey_root_list/",JourneyRootList.as_view(),name="journey_root_list"),
    path("admin_details_update/<int:id>/",AdminDetailsUpdate.as_view(),name="admin_details_update"),
    path("common_user_update/<int:id>/",CommonUserUpdate1.as_view(),name="common_user_update"),
    path("staff_details_update/<int:id>/",StaffDetailsUpdate.as_view(),name="staff_details_update"),
    path("bus_list_update/<int:id>/",BusListUpdate.as_view(),name="bus_list_update"),
    path("journey_root_list_update/<int:id>/",JourneyListUpdate.as_view(),name="journey_root_list_update"),
    path("delete/<int:id>/",DeleteProfile.as_view(),name="delete/"),
    path("delete_bus/<int:id>/",BusDetailsDelete.as_view(),name="delete_bus"),
    path("ticket_delete/<int:id>/",DeleteTicket,name="ticket_delete"),
    path("common-user-list/",CommonUserList.as_view(),name="common-user-list"),
    path("delete_jur/<int:id>/",JourneyRootDeleteList.as_view(),name="delete_jur"),
]